-- Premier fichier de création de table en BDD pour le projet Final Fantasy : Les voyages
-- Contient les tables Users, coinInventory, Teams, IdlePersonnageBase, IdlePersonnagesFromUsers


BEGIN;

DROP TABLE IF EXISTS "idleCharacterFromUsers",
"idleCharacterBase",
"teams",
"coinInventory",
"users" CASCADE;


CREATE TABLE IF NOT EXISTS "users" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nickname" VARCHAR(64) NOT NULL UNIQUE,
    "email" VARCHAR(64) NOT NULL UNIQUE,
    "password" VARCHAR(55) NOT NULL,
    "is_admin" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "coinInventory" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "gils" INT NOT NULL DEFAULT 0,
    "travelxp" INT NOT NULL DEFAULT 0,
    "users_id" INT REFERENCES "users"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "teams" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "openSlot" INT NOT NULL,
    "users_id" INT REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "idleCharacterBase" (
    "id" GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(64) NOT NULL,
    "travelImage" VARCHAR(100) NOT NULL UNIQUE,
    "portraitImage" VARCHAR(100) NOT NULL UNIQUE,
    "cost" INT NOT NULL,
    "growth_rate" DECIMAL(10,5) NOT NULL,
    "travelClickPower" INT NOT NULL,
    "order" INT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "idleCharacterFromUsers" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "currentLevel" INT NOT NULL,
    "currentlyInTeam" BOOLEAN DEFAULT FALSE
);

COMMIT;

 